# Generated by Django 5.2.5 on 2025-08-08 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaEstoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='preco',
            field=models.FloatField(default=0),
        ),
    ]
